---
driver:
  name: ec2
  aws_ssh_key_id:
  region: eu-west-1
  availability_zone: a
  instance_type: t2.micro
  security_group_ids:
  subnet_id:
  retryable_tries: 120
  tags: {
    Name: "cis-el7-l1-hardening-kitchen",
    created-by: "test-kitchen"
  }

provisioner:
  name: chef_solo

platforms:
  - name: rhel-7

verifier:
  name: inspec
  sudo: true

transport:
  ssh_key: 

suites:
  - name: default
    run_list:
      - recipe[cis-el7-l1-hardening::enable_sudo_no_tty]
      - recipe[cis-el7-l1-hardening::default]
