name 'cis-el7-l1-hardening'
maintainer 'The Authors'
maintainer_email 'emea-saleseng@chef.io'
license 'all_rights'
description 'Installs/Configures cis-el7-l1-hardening'
long_description 'Installs/Configures cis-el7-l1-hardening'
issues_url 'https://github.com/chef-customers/cis-el7-l1-hardening/issues'
source_url 'https://github.com/chef-customers/cis-el7-l1-hardening'
version '0.5.0'

depends 'line', '~> 0.6.3'
